### ISSUE TITLE
Support org based published plugins

### ISSUE THREAD

**Issue by basiclines** [yuanqing/figma-plugins-stats#2]
First of all, thank you for this CLI! Is an awesome idea and gives some visibility about our stats as plugin creators!

When you publish a plugin using an organization plan,  the plugins rest api provides an additional field `author_org`, which provides the organization id and name that actually holds the plugin ownership and that is what is actually is shown to the users in the plugin page.

i.e:
https://www.figma.com/community/plugin/822809274991177560/Frametastic

Currently I'm not able to fetch this plugin data trough your CLI as`npx figma-plugins-stats cabify` doesn't holds any plugin, and `npx figma-plugins-stats Ismael Gonzalez` looks like an invalid username.

Is there any chance you can support the org plan plugins?

**Comment by yuanqing** [comment]
The fix was easy enough!

```
$ npx figma-plugins-stats@0.0.12 cabify
npx: installed 84 in 5.115s

  period  7d
  from    2020-04-07 14:04:38 UTC+8
  to      2020-04-15 01:35:19 UTC+8

  no  name         author           installs         likes
  1   Frametastic  Ismael Gonzalez  █▃▂▄▂▄▂ 186 ↑84  █▂▁▁▁▁▂ 18 ↑6

                   totals           █▃▂▄▂▄▂ 186 ↑84  █▂▁▁▁▁▂ 18 ↑6

```
