### ISSUE TITLE
Doesn't return the numbers.

### ISSUE THREAD

**Issue by pawelkontek** [yuanqing/figma-plugins-stats#6]
The script worked flawlessly, but recently I am getting:
`User `xyz` has no public plugins`

For your user it returns just one plugin, but you do have more: 
<img width="653" alt="image" src="https://user-images.githubusercontent.com/7879784/168996704-4f5a707c-23ef-46eb-a591-b948619082d4.png">

**Comment by gnchrv** [comment]
I have a similar problem. The script returns just one plugin whereas I have two. Some time ago it worked well and returned both of them.

`npx --yes -- figma-plugins-stats gnchrv`

<img width="820" alt="image" src="https://user-images.githubusercontent.com/10423326/169028017-99d30c75-0dc7-4454-ad54-c12e054f6950.png">

**Comment by klavsbuss** [comment]
@yuanqing Starting from May 12, only 50 plugin data is within json - e.g. [2022-05-12.json](https://github.com/yuanqing/figma-plugins-stats/blob/gh-pages/2022-05-12.json)
![image](https://user-images.githubusercontent.com/18184893/169285732-d9f65c9e-c08d-4209-b419-55c43ca7f9fc.png)

**Comment by pawelkontek** [comment]
@klavsbuss do you maybe know why that's the case? Does it seem that the change was made around FigJam?

**Comment by klavsbuss** [comment]
@pawelkontek no idea, haven't had time to check this out

**Comment by yuanqing** [comment]
This issue should be fixed as of `figma-plugins-stats@0.0.24`. Note that data was incorrect from 12 May 2022 to 5 June 2022 – the data files for these particular dates are a copy of the data file for 11 May 2022

**Comment by klavsbuss** [comment]
Thanks @yuanqing much appreciated! 🙏

**Comment by pawelkontek** [comment]
@yuanqing running the command in the terminal produces the same effect (User `xxx` has no public plugins). In your case it shows only one plugin data.

**Comment by klavsbuss** [comment]
@pawelkontek tried on figmastats.com and it returns everything as expected (i am using same db). could be that problem is on your side?
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/18184893/172568639-abfd8a0d-bab2-4cad-a2bd-c1eb92b0c774.png">

**Comment by yuanqing** [comment]
@pawelkontek – You need to make sure that you’re running `0.0.24`:

```
npx --yes -- figma-plugins-stats@0.0.24 kontek
```

**Comment by pawelkontek** [comment]
Ah, yes, now I see! Thank you @yuanqing, you are a amazing!

**Comment by pawelkontek** [comment]
<img width="472" alt="image" src="https://user-images.githubusercontent.com/7879784/175933218-f77e39b0-b9e2-4abb-8b3d-efc3e8bc455c.png">
@yuanqing I hate to bring this to you, but it seems that it doesn't work :(

**Comment by yuanqing** [comment]
You need to use `0.0.25` 😄

```
npx --yes -- figma-plugins-stats@latest kontek
```

**Comment by pawelkontek** [comment]
Thanks, @yuanqing, you are the best!
