### ISSUE TITLE
Number of Installs vs Number of Users in new a recent Figma Release

### ISSUE THREAD

**Issue by pawelkontek** [yuanqing/figma-plugins-stats#7]
Now, with the recent changes to the plugins, they don't need to actually be installed, and Figma seems to count the "number of the user (I guess?)":
<img width="355" alt="image" src="https://user-images.githubusercontent.com/7879784/176520996-2cc0ded0-1c93-4c52-8428-780063cfad3b.png">

Eg. Figma plugin's community page shows 568 "users", while the actuall number of "installs" in returned by your script shows 280:
<img width="310" alt="image" src="https://user-images.githubusercontent.com/7879784/176521182-f0aa3661-c685-4fae-b183-fb11876075f2.png">

Are you considering updating the script, so it will show also the new "users" count?

**Comment by yuanqing** [comment]
Just added this in `0.0.26`!

```
npx --yes -- figma-plugins-stats@latest
```
