### ISSUE TITLE
"Cannot read properties of undefined (reading 'plugins')"

### ISSUE THREAD

**Issue by pawelkontek** [yuanqing/figma-plugins-stats#8]
<img width="439" alt="image" src="https://user-images.githubusercontent.com/7879784/182016103-7e5ddefd-be18-4864-8ec5-d7a5de5aab19.png">

**Comment by yuanqing** [comment]
@pawelkontek – Hey! I’ve made the decision to permanently deprecate and cease maintenance of `figma-plugins-stats` due to the high API churn and low community usage. It was a good run
